#if !canImport(ObjectiveC)
import XCTest

extension KeychainFunctionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__KeychainFunctionTests = [
        ("testAdd", testAdd),
        ("testAddThrows", testAddThrows),
        ("testCopy", testCopy),
        ("testCopyNil", testCopyNil),
        ("testDeleteThrows", testDeleteThrows),
        ("testSetAgain", testSetAgain),
        ("testSet", testSet),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(KeychainFunctionTests.__allTests__KeychainFunctionTests),
    ]
}
#endif
